### ISSUE TITLE
`PatchProps` could allow user input

### ISSUE THREAD

**Issue by bhvieira** [chrisadamsonmcri/freesurfer_statsurf_display#1]
Hi, first I'd like to thank you for this tool which really makes the job of plotting statistical data onto Freesurfer surfaces way easier (instead of the lengthy process of generating the .annot files and calling tksurfer to display the annotated surfaces).

As a suggestion, I think the lightning of the scene could allow some user input. Specifically, `PatchProps` could accept user input at `freesurfer_statsurf_plot.m`.

Thanks!

**Comment by chrisadamsonmcri** [comment]
Added support for this as a name/value pair cell array argument to all plotting functions.
There is no checking of those values so if you get errors to do with patch... then check the values you put in that cell array.

Thanks for the kind words.
